[package]
name = "cspuz_gen"
version = "0.1.0"
edition = "2021"

[lib]
name = "cspuz_gen"
crate-type = ["cdylib", "lib"]

[dependencies]
cspuz_core = { path = "../../../../cspuz_core/cspuz_core", default-features = false }
cspuz_rs = { path = "../../../../cspuz_core/cspuz_rs", default-features = false, features = ["generator"] }
cspuz_rs_puzzles = { path = "../../../../cspuz_core/cspuz_rs_puzzles", default-features = false }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0"
rand = { version = "0.8.5" }
