name: Checks (puzzle-board)

on:
  pull_request:
    paths:
      - 'packages/puzzle-board/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - uses: actions/checkout@v4
    - name: Setup pnpm
      run: |
        npm install -g pnpm@10.18.2
        pnpm setup
    - name: Lint
      run: |
        pnpm --filter puzzle-board install --frozen-lockfile
        pnpm --filter puzzle-board run format-check
        pnpm --filter puzzle-board run lint
