name: Checks (Sudoku Editor)

on:
  pull_request:
    paths:
      - 'packages/sudoku-editor/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - uses: actions/checkout@v4
    - name: Setup pnpm
      run: |
        npm install -g pnpm@10.18.2
        pnpm setup
    - name: Lint
      run: |
        pnpm --filter sudoku-editor install --frozen-lockfile
        pnpm --filter sudoku-editor run format-check
        pnpm --filter sudoku-editor run lint
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - uses: actions/checkout@v4
    - name: Setup pnpm
      run: |
        npm install -g pnpm@10.18.2
        pnpm setup
    - name: Test
      run: |
        pnpm --filter sudoku-editor install --frozen-lockfile
        pnpm --filter sudoku-editor run test
